site_name: PraxisLIVE v5 documentation
nav:
  - 'PraxisLIVE v5': 'index.md'
  - 'Getting started':
    - 'Installation': 'installation.md'
    - 'Example projects': 'examples.md'
    - 'Architecture & terminology': 'architecture.md'
    - 'Main interface': 'main-interface.md'
  - 'Visual project building':
    - 'Projects': 'projects.md'
    - 'Editors': 'editors.md'
    - 'Graph editor': 'editors-graph.md'
    - 'GUI editor': 'editors-gui.md'
    - 'MIDI editor': 'editors-midi.md'
    - 'OSC editor': 'editors-osc.md'
    - 'Component editors': 'component-editors.md'
    - 'Custom components': 'custom-components.md'
  - 'Code editing':
    - 'Coding in PraxisLIVE': 'coding.md'
    - 'Coding core components': 'coding-core.md'
    - 'Coding audio components': 'coding-audio.md'
    - 'Coding video components': 'coding-video.md'
    - 'Coding OpenGL video components': 'coding-video-gl.md'
    - 'Coding TinkerForge components': 'coding-tinkerforge.md'
    - 'Properties & animation': 'coding-properties.md'
    - 'Annotations': 'coding-annotations.md'
    - 'Additional annotations': 'coding-annotations-extra.md'
    - 'Linkables': 'coding-linkables.md'
    - 'References': 'coding-ref.md'
    - 'Data Pipes': 'coding-data-pipes.md'
    - 'Shared code': 'coding-shared.md'
    - 'Third-party libraries': 'coding-libraries.md'
  - 'Built-in components':
    - 'Core components': 'components-core.md'
    - 'Audio components': 'components-audio.md'
    - 'Video components': 'components-video.md'
    - 'GUI components': 'components-gui.md'
  - 'Advanced usage':
    - 'Command line usage': 'cli-usage.md'

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: 'blue grey'
      accent: 'blue'
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  logo: 'img/praxislive-icon.png'
  favicon: 'img/favicon.ico'
  
site_author: ""

extra_css:
    - custom.css

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/praxis-live'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/praxislive'

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

#repo_url: https://github.com/praxis-live/support


