site_name: Praxis LIVE documentation
pages:
  - 'index.md'
  - 'Getting started':
    - 'Installation': 'installation.md'
    - 'Example projects': 'examples.md'
    - 'Architecture & terminology': 'architecture.md'
    - 'Main interface': 'main-interface.md'
    - 'Projects': 'projects.md'
    - 'Editors': 'editors.md'
    - 'Component editors': 'component-editors.md'
    - 'Custom components': 'custom-components.md'
  - 'Built-in components':
    - 'Core components': 'components-core.md'
    - 'Audio components': 'components-audio.md'
    - 'Video components': 'components-video.md'
    - 'GUI components': 'components-gui.md'
  - 'Creating custom components':
    - 'Coding in Praxis LIVE': 'coding.md'
    - 'Coding core components': 'coding-core.md'
    - 'Coding audio components': 'coding-audio.md'
    - 'Coding video components': 'coding-video.md'
    - 'Coding OpenGL video components': 'coding-video-gl.md'
    - 'Coding TinkerForge components': 'coding-tinkerforge.md'
    - 'Properties & animation': 'properties.md'
    - 'Annotations': 'annotations.md'
    - 'Additional annotations': 'annotations-additional.md'
  - 'Advanced usage':
    - 'Command line player': 'cli-player.md'
    - 'Distributed hubs': 'distributed-hubs.md'
    - 'Terminal': 'terminal.md'

theme: readthedocs

site_author: ""

repo_url: https://github.com/praxis-live/support

include_search: true

extra_css:
    - custom.css

#use_directory_urls: false

